---
title: "esm_244_lab_1"
author: "E.M.Thomas"
date: "2023-01-12"
output: html_document
---

```{r setup, include=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE) #does it for every code chunk

library(tidyverse)
library(here)
library(sf) #good for working with spatial data
library(tmap) #works well with sf for data visualization 
```

### Read in data

```{r}
sf_trees <- read_csv(here('data', 'sf_trees', 'sf_trees.csv')) #read_csv is improved version of read.csv which is built into Rstudio. read_ is faster, makes the final data easier to work with 

top_5_status <- sf_trees %>% 
  group_by(legal_status) %>% 
  summarize(tree_count = n()) %>% 
  slice_max(tree_count, n=5) %>% 
  arrange(-tree_count)

ggplot(data=top_5_status, aes(x=fct_reorder(legal_status, tree_count),
                              y=tree_count)) + geom_col() + 
  labs(y='Tree count', x='Legal status') + 
  coord_flip() +
  theme_minimal()#fct_reorder reorders the x values (legal_status) by tree_count
```



